### ISSUE TITLE
@key directive not emitted in SDL

### ISSUE THREAD

**Issue by molaughlen** [apollographql/federation-hotchocolate#66]
I noticed that the SDL doesn't include the @key directive on classes that are adorned with the KeyAttribute.  This occurs for both the ChilliCream and Apollo GraphQL implementations.  What am I missing here?

Emitted SDL
```
directive @key(fields: _FieldSet!) repeatable on OBJECT | INTERFACE

scalar _Any

union _Entity = Product

type _Service {
  sdl: String!
}

scalar _FieldSet

type Query {
  book: Book!
  _service: _Service!
  _entities(representations: [_Any!]!): [_Entity]!
}

type Product {
  id: ID!
  name: String!
  price: Float!
}

type Book {
  title: String!
  author: Author!
}

type Author {
  name: String!
}
```

Code
```

using ApolloGraphQL.HotChocolate.Federation;

namespace HotChocolate.Apollo.Sample;

public class Book
{
    public string Title { get; set; }

    public Author Author { get; set; }
}

public class Author
{
    public string Name { get; set; }
}

[Key("id")]
public class Product
{
    [ID]
    public string Id { get; set; }

    public string Name { get; set; }

    public float Price { get; set; }

    [ReferenceResolver]
    public static Product? ResolveReference(
        // Represents the value that would be in the Id property of a Product
        string id
    )
    {
        return new Product()
        {
            Id = id,
            Name = $"Name of {id}",
            Price = 1f
        };
    }
}


public class Query
{
    public Book GetBook() =>
        new Book
        {
            Title = "C# in depth.",
            Author = new Author
            {
                Name = "Jon Skeet"
            }
        };
}

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddGraphQLServer()
    .AddApolloFederationV2()
    .AddQueryType<Query>()
    .AddType<Product>();


var app = builder.Build();

app.MapGraphQL();

app.Run();

```

**Comment by smyrick** [comment]
The issue is that regular GraphQL introspection does not include directive metadata. This is a current limitation of the main GraphQL spec.

There are two ways around this.
First you can generate the SDL at build time with reflection that include the metadata: https://github.com/apollographql/federation-hotchocolate?tab=readme-ov-file#generating-schema-at-build-time


Or you can start up at runtime and use [Rover](https://www.apollographql.com/docs/rover/commands/subgraphs#subgraph-introspect) to query a Federation specific field `{ _service { sdl } }` which include the full SDL with directives

Can you verify those work before we close?

**Comment by molaughlen** [comment]
I confirmed that queriying via _service { sdl } included the directives.  Thank you for the prompt response

**Comment by smyrick** [comment]
Great! You can automate that call with `rover subgraph introspect` so you can pipe it right into the check and publish command if needed

https://www.apollographql.com/docs/rover/commands/subgraphs#subgraph-introspect
