### ISSUE TITLE
How to extend a type from on subgraph into another

### ISSUE THREAD

**Issue by rquackenbush** [apollographql/federation-hotchocolate#74]
# What

I'm trying to extend another type using GraphQL federation under using the following syntax:

```c#
[Key("id")]
[Extends]
public class Parent
{
    [ID]
    public string Id { get; set; }

    public List<Child> Children()
    {
        return new List<Child>
        {
            new Child("1", "Child 1"),
            new Child("2", "Child 2")
        };
    }
}
```

And the following registration code:

```c#
   .AddTypeExtension<Parent>()
```
Is what I'm trying to do possible? If so, what am I doing wrong?

# Repro
I have created a minimal reproduction of my scenario here:
https://github.com/rquackenbush/apollo-federation-repro

**Comment by dariuszkuc** [comment]
Hello 👋 
Each subgraph declares `Parent` as its own type -> there is no need for `[Extends]` directive marker (it was required for fed v1 it is not needed for v2) nor registering any type extensions. From subgraph perspective it is just a regular type that has some extra directives applied to it. Those extra directives are then used by the composition process to compose your supergraph.

FYI since `Parent` type is an entity, you also need to register the entity resolvers -> see our [README](https://github.com/apollographql/federation-hotchocolate?tab=readme-ov-file#annotation) and/or [HotChocolate docs](https://chillicream.com/docs/hotchocolate/v13/api-reference/apollo-federation/#define-a-reference-resolver). You can also take a look at the examples in this repo.

For more details about Federation and entities refer to our [docs](https://www.apollographql.com/docs/federation/entities). We also have tutorials about .NET/HotChocolate and Federation -> [intro](https://www.apollographql.com/tutorials/intro-hotchocolate) and [federation](https://www.apollographql.com/tutorials/federation-hotchocolate) that covers those topics in detail.

**Comment by rquackenbush** [comment]
Thank you for the push in the right direction! I've updated my example and it's now working.
